# Generated by Django 5.2.3 on 2025-06-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_tittle', models.CharField(max_length=60)),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
