# Generated by Django 5.0.1 on 2025-07-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stu_class', models.IntegerField()),
                ('stu_age', models.IntegerField()),
            ],
        ),
    ]
