# Generated by Django 5.0.1 on 2025-08-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_user_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='post/1.png', upload_to='post/'),
        ),
    ]
