# Generated by Django 5.0.1 on 2025-07-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
