# Generated by Django 5.0.1 on 2025-07-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library2', '0002_book_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
    ]
